services:
  api:
    container_name: philoagents-api
    build:
      context: ./philoagents-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./philoagents-api/.env
    volumes:
      - ./philoagents-api/src/philoagents:/app/philoagents
    networks:
      - philoagents-network
  ui:
    container_name: philoagents-ui
    build:
      context: ./philoagents-ui
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./philoagents-ui:/app
      - /app/node_modules
    depends_on:
      - api
    networks:
      - philoagents-network

networks:
  philoagents-network:
    name: philoagents-network
